# This workflow run all the cases found in the pypower folder

name: Run test cases

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: python3 -m pip install --upgrade pip -r requirements.txt
      
    - name: Run test cases
      run: python3 tests/test_cases.py

    - name: Upload artifacts on failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-results
        path: |
          tests/
